---
version: '3.7'
services:
  build_poject:
    build:
      context: build/
    volumes:
    - type: volume
      source: artifacts
      target: /tmp/hw12/target

  deploy_project:
    image: tomcat:9-jre11
    volumes:
    - type: volume
      source: artifacts
      target: /usr/local/tomcat/webapps
    ports:
    - 8080:8080
    depends_on: 
    - build_poject

  db:
    image: mariadb:10.11
    ports:
    - 3306:3306

volumes:
  artifacts: