---
version: '3.7'
services:
  build_poject:
    build:
      context: build/
    volumes:
    - type: volume
      source: artifacts
      target: /root/boxfuse-sample-java-war-hello/target

  deploy_project:
    build:
      context: deploy/
    volumes:
    - type: volume
      source: artifacts
      target: /usr/local/tomcat/webapps
    ports:
    - 8080:8080
    depends_on: 
    - build_poject

volumes:
  artifacts: