---
version: '3.7'
services:
  build_poject:
    build:
      context: build/
    volumes:
    - type: volume
      source: artifacts
      target: /tmp/hw12/target

  web:
    image: tomcat:9-jre11
    volumes:
    - type: volume
      source: artifacts
      target: /usr/local/tomcat/webapps
    ports:
    - 8080:8080
    depends_on: 
    - build_poject
    links:
    - "db:dd"

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dd
    ports:
    - 3306:3306

volumes:
  artifacts: