---
version: '3.7'
services:
  build:
    context: /build
  volume:
  - type: volume
    source: artifacts
    targer: /root/DO_edu-HW12_CP/target

  deploy:
    context: /deploy
  volumes:
  - type: volume
    source: artifacts
    targer: /usr/local/tomcat/webapps
  ports:
  - 8080:8080
  depends_on: 
  - build

volumes:
  artifacts:
