---
version: '3.7'
services:
  build_project:
    build:
      context: build/
    volumes:
    - type: volume
      source: artifacts
      target: /tmp/hw12

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: demo_hw12_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
    - 3306:3306
    depends_on:
    - build_project
  
  web:
    image: tomcat:6.0-jre8
    volumes:
    - type: volume
      source: artifacts
      target: /usr/local/tomcat/webapps
    ports:
    - 8080:8080
    depends_on: 
    - db
    links:
    - db:demo_hw12_db

volumes:
  artifacts: